version: "3.8"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./server:/usr/share/nginx/html/
    ports:
      - 8081:8080
  gee:
    build: .
    volumes:
      - ./server:/app/server/